quarkus.application.name=rem.tech.desk
quarkus.application.version=1.0.0

quarkus.http.host=192.168.88.2
quarkus.http.port=5679

quarkus.log.level=INFO
quarkus.log.category."jakarta.ws.rs".level=DEBUG

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.format-sql=true
quarkus.hibernate-orm.log.sql=true

quarkus.datasource.db-kind=PostgreSQL
quarkus.datasource.username=iMynthon
quarkus.datasource.password=ZQMM
quarkus.datasource.jdbc.url=jdbc:postgresql://192.168.88.2:5436/rem_tech_desk_db

quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations =db/migration
quarkus.flyway.clean-at-start=true
quarkus.flyway.default-schema=tech_desk_schema